// <auto-generated />
using System;
using Database_12_12day19.ApplicationDbcontexet;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database_12_12day19.Migrations
{
    [DbContext(typeof(ApplicationCompanyDBContact))]
    [Migration("20231213091247_oneToMany1")]
    partial class oneToMany1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Database_12_12day19.Modeels.DepartmentEmp", b =>
                {
                    b.Property<int>("DepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepId"), 1L, 1);

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.HasKey("DepId");

                    b.ToTable("DepartmentEmps");
                });

            modelBuilder.Entity("Database_12_12day19.Modeels.EmployeeInformation", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DepId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("DepId");

                    b.ToTable("EmployeeInformations");
                });

            modelBuilder.Entity("Database_12_12day19.Modeels.Project", b =>
                {
                    b.Property<int>("projID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("projID"), 1L, 1);

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("projName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("projID");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("EmployeeInformationProject", b =>
                {
                    b.Property<int>("EmployeeInformationsEmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("projectsprojID")
                        .HasColumnType("int");

                    b.HasKey("EmployeeInformationsEmployeeID", "projectsprojID");

                    b.HasIndex("projectsprojID");

                    b.ToTable("EmployeeInformationProject");
                });

            modelBuilder.Entity("Database_12_12day19.Modeels.EmployeeInformation", b =>
                {
                    b.HasOne("Database_12_12day19.Modeels.DepartmentEmp", "departmentEmp")
                        .WithMany("EmployeeInformations")
                        .HasForeignKey("DepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departmentEmp");
                });

            modelBuilder.Entity("EmployeeInformationProject", b =>
                {
                    b.HasOne("Database_12_12day19.Modeels.EmployeeInformation", null)
                        .WithMany()
                        .HasForeignKey("EmployeeInformationsEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database_12_12day19.Modeels.Project", null)
                        .WithMany()
                        .HasForeignKey("projectsprojID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Database_12_12day19.Modeels.DepartmentEmp", b =>
                {
                    b.Navigation("EmployeeInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
